### ISSUE TITLE
HTTPS complains about secure WebSocket protocol (wss)

### ISSUE THREAD

**Issue by bsides** [ZCube/ACTWebSocket#21]
Hello!,

First of all thanks for this plugin, it's amazing the stuff we can do with it.

Now for the request. Right now my overlay ([repo](https://github.com/bsides/horizoverlay) | [overlay](https://bsides.github.io/horizoverlay)) doesn't work with it because Chrome complains the connection comes from a secure connection (https) but the websocket is from an unsecure connection (ws should be wss). I tried to tick the SSL option in the ActWebSocket plugin but it still throws errors, probably because it needs the same certificate from HTTPS?

`WebSocket connection to 'wss://192.168.0.4:10501/MiniParse' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID`

How could I manage to get it working? It's hard to find any service without the secure layer these days.

 Thanks in advance.

**Comment by zcube** [comment]
First, there are four ways to avoid the wss problem.

1. Use localhost

2. Issuing SSL certificates using Let's Encrypt

Problem: It requires Domain and 80 ports. It's too cumbersome to ask users for it.

3. Issue a private certificate and install it in Windows

Problem: It works when it is tested. But I did not apply because it seems to be a security problem.

4. Support for separate overlay tools

Problem: I controlled the SSL authentication check with a program option in a tool called OverlayProc. However, it does not work without OverlayProc.

I've reviewed SSL-related support before.

Besides, I do not play FF14 anymore. That makes it hard to support this issue.

The recommended way to do this is to use localhost or use a separate tool like Træfik to do SSL termination for external streaming. When using SSL feature of ACTWebSocket, it is supposed to issue a self-signed certificate, but there will be a problem issuing different certificate each time.

With Google translator ..

**Comment by zcube** [comment]
Alternatively, if you reverse proxy the GitHub page using localhost, this also works.

**Comment by zcube** [comment]
I add reverse proxy for github.io
You can use it likes http://localhost:10501/github/bsides/horizoverlay/

**Comment by bsides** [comment]
Thanks for the awesome support @ZCube, I’ll try the reverse proxy option. It’s weird how the web is evolving into a secure but boring at the same time for us developers, uh? Regardless, thanks for your time, I know how hard it is to support something as you don’t play FFXIV anymore. Regards from Brazil!

**Comment by zcube** [comment]
Reverse proxy via http is not a secure method. Security always makes it more difficult for developers and users. You can implement SSL properly if you require a domain (including ddns) and 80,443 ports for all users, or if you can install a self-signed certificate on the user's system. Otherwise, I think this is the last method to be left. If SSL is really needed, it is right to consider other options.

It was an overlay made better than I thought. So today, it is a substitute holiday, so I made some changes. I hope this helps a little with your overlay.

**Comment by EvilSakray** [comment]
@bsides Thanks, I'll give it a try when I'm back from holidays.
