### ISSUE TITLE
Add Support for Number Formatting

### ISSUE THREAD

**Issue by austinrr** [ZCube/ACTWebSocket#23]
As of https://advancedcombattracker.com/version.php version 3.3.2.257 there is now additional options for number formatting such as `{ENCDPS-*} may show '1000K' and {encdps-*} may show '1.00M'`.  

Could we get these attributes added as well as any other new formatting options?

**Comment by lalafellsleep** [comment]
this issue is on overlay's javascript. not plugin issue. if you want new feature, contact overlay maker first, please

if you really want this option, edit below .cs file there https://github.com/ZCube/ACTWebSocket/blob/1d89d850f95348a5b1504a25b2bd9eb8683703e4/ACTWebSocket.Core/Functions/OverlayDataSender.cs#L293-L319
